version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html/estrategastest #establecer area de trabajo 
    volumes:
      - ./:/var/www/html/estrategastest
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html/estrategastest
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/ssl/:/etc/nginx/ssl/

    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: osmel
      MYSQL_DATABASE: basedatos
      MYSQL_ROOT_PASSWORD: osmel5458
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#PHPMyAdmin Service
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
    - "7000:80"
    links:
    - db:db
    environment:
      MYSQL_USER: osmel
      MYSQL_PASSWORD: osmel5458
      MYSQL_ROOT_PASSWORD: osmel5458
      UPLOAD_LIMIT: 3000000000
    networks:
    - app-network


#cerbot Service
#certbot:
#    image: certbot/certbot
#    container_name: certbot
#    volumes:
#      - certbot-etc:/etc/letsencrypt
#      - certbot-var:/var/lib/letsencrypt
#      - web-root:/var/www/html/estrategastest
#    depends_on:
#      - webserver
#    command: certonly --webroot --webroot-path=/var/www/html/estrategastest --email osmel.calderon@gmail.com --agree-tos --no-eff-email --staging -d estrategastest.com  -d www.estrategastest.com    

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local

#dhparam:
#    driver: local
#    driver_opts:
#      type: none
#      device: /var/www/html/estrategastest/dhparam/
#      o: bind

